/**
 * Regenerates types/supabase.ts from the linked Supabase project and applies
 * three deterministic patches that the raw generator output requires:
 *
 *   1. Strips any `npm warn ...` lines that npm writes to stdout.
 *   2. Injects the `log_activity` RPC function into the Functions block.
 *      (The function exists in the DB but is not visible to the type generator
 *       because it is defined with SECURITY DEFINER and the introspection role
 *       cannot see its argument list.)
 *   3. Appends named type aliases for all public enums so feature modules can
 *      import `ProjectStatus` etc. without spelling out the full
 *      Database['public']['Enums']['...'] path.
 *
 * Usage:  pnpm db:types
 */

import { execSync }    from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath }   from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT  = resolve(ROOT, 'types', 'supabase.ts')

// ─── 1. Generate ──────────────────────────────────────────────────────────────

console.log('Generating Supabase types…')
let raw
try {
  raw = execSync('npx supabase gen types typescript --linked', {
    cwd:      ROOT,
    encoding: 'utf-8',
    // Capture stderr separately so only actual TS output lands in `raw`.
    // npm prints its "warn" lines to stdout in some versions; strip them below.
    stdio:    ['inherit', 'pipe', 'pipe'],
  })
} catch (err) {
  console.error('supabase gen types failed:', err.stderr ?? err.message)
  process.exit(1)
}

// ─── 2. Strip npm noise ───────────────────────────────────────────────────────

const lines = raw.split('\n')
const cleaned = lines
  .filter((l) => !l.startsWith('npm warn') && !l.startsWith('npm notice'))
  .join('\n')
  .trimStart()   // remove any leading blank line left after stripping

// ─── 3. Inject log_activity into Functions block ─────────────────────────────
//
// log_activity is a SECURITY DEFINER function not visible to the type generator
// (its introspection role cannot see the argument list). Inject it manually
// before the closing brace of the Functions block.
//
// Strategy: match `\n    }\n    Enums: {` — the unique double-close that ends
// Functions in the generated output, regardless of which auto-generated
// functions precede it (the list grows as new SECURITY-DEFINER-free RPCs
// are added, so we anchor on the closing boundary, not on a sibling function).

const LOG_ACTIVITY_TYPE = `\
      log_activity: {
        Args: {
          p_organization_id: string
          p_entity_type:     string
          p_entity_id:       string
          p_activity_type:   string
          p_metadata?:       Json | null
        }
        Returns: void
      }`

const patched = cleaned.replace(
  /(\n    \})\n(\s+Enums: \{)/,
  `\n${LOG_ACTIVITY_TYPE}$1\n\n$2`
)

if (patched === cleaned) {
  console.warn(
    'WARNING: Could not find insertion point for log_activity. ' +
    'The Functions block structure may have changed. Skipping injection.'
  )
}

// ─── 4. Append named type aliases ────────────────────────────────────────────

const ALIASES = `

// ─── Convenience type aliases ─────────────────────────────────────────────────
// Re-export database enum types as named aliases so feature modules can import
// them without referencing Database['public']['Enums']['...'] directly.
// Generated by scripts/gen-types.mjs — do not edit this block manually.

export type ActivityType      = Database['public']['Enums']['activity_type']
export type AssetType         = Database['public']['Enums']['asset_type']
export type ClientStatus      = Database['public']['Enums']['client_status']
export type InvoiceStatus     = Database['public']['Enums']['invoice_status']
export type OrgRole           = Database['public']['Enums']['org_role']
export type PaymentStatus     = Database['public']['Enums']['payment_status']
export type ProjectPriority   = Database['public']['Enums']['project_priority']
export type ProjectStatus     = Database['public']['Enums']['project_status']
export type TaskStatus        = Database['public']['Enums']['task_status']

// Tasks reuse project_priority for their priority field (no separate task_priority enum).
export type TaskPriority      = Database['public']['Enums']['project_priority']

// project_members.role is stored as plain text (no dedicated enum in the schema).
export type ProjectMemberRole = string
`

const final = patched.trimEnd() + '\n' + ALIASES

// ─── 5. Write ─────────────────────────────────────────────────────────────────

writeFileSync(OUT, final, 'utf-8')
console.log(`✓ Written to ${OUT}`)
